# Generated by Django 2.2.1 on 2019-05-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190507_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
